CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username VARCHAR(255) NOT NULL,
       	password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS searches (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	search_type VARCHAR(255) NOT NULL,
	user_input VARCHAR(MAX) NOT NULL,
	user_output VARCHAR(MAX) NOT NULL,
	user_id INTEGER
);

CREATE TABLE IF NOT EXISTS favorites (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	favorite VARCHAR(255) NOT NULL,
	search_id INTEGER
);

CREATE TABLE IF NOT EXISTS locations (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	location VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id),
	location_id INTEGER NOT NULL,
	FOREIGN KEY(location_id) REFERENCES locations(id)
); 
